#!/bin/sh

#   siena_flirt - Registration part of SIENA
#
#   Stephen Smith and Mark Jenkinson, FMRIB Image Analysis Group
#
#   Copyright (C) 1999-2004 University of Oxford
#
#   Part of FSL - FMRIB's Software Library
#   http://www.fmrib.ox.ac.uk/fsl
#   fsl@fmrib.ox.ac.uk
#   
#   Developed at FMRIB (Oxford Centre for Functional Magnetic Resonance
#   Imaging of the Brain), Department of Clinical Neurology, Oxford
#   University, Oxford, UK
#   
#   
#   LICENCE
#   
#   FMRIB Software Library, Release 4.0 (c) 2007, The University of
#   Oxford (the "Software")
#   
#   The Software remains the property of the University of Oxford ("the
#   University").
#   
#   The Software is distributed "AS IS" under this Licence solely for
#   non-commercial use in the hope that it will be useful, but in order
#   that the University as a charitable foundation protects its assets for
#   the benefit of its educational and research purposes, the University
#   makes clear that no condition is made or to be implied, nor is any
#   warranty given or to be implied, as to the accuracy of the Software,
#   or that it will be suitable for any particular purpose or for use
#   under any specific conditions. Furthermore, the University disclaims
#   all responsibility for the use which is made of the Software. It
#   further disclaims any liability for the outcomes arising from using
#   the Software.
#   
#   The Licensee agrees to indemnify the University and hold the
#   University harmless from and against any and all claims, damages and
#   liabilities asserted by third parties (including claims for
#   negligence) which arise directly or indirectly from the use of the
#   Software or the sale of any products based on the Software.
#   
#   No part of the Software may be reproduced, modified, transmitted or
#   transferred in any form or by any means, electronic or mechanical,
#   without the express permission of the University. The permission of
#   the University is not required if the said reproduction, modification,
#   transmission or transference is done without financial return, the
#   conditions of this Licence are imposed upon the receiver of the
#   product, and all original and amended source code is included in any
#   transmitted product. You may be held legally responsible for any
#   copyright infringement that is caused or encouraged by your failure to
#   abide by these terms and conditions.
#   
#   You are not permitted under this Licence to use this Software
#   commercially. Use for which any financial return is received shall be
#   defined as commercial use, and includes (1) integration of all or part
#   of the source code or the Software into a product for sale or license
#   by or on behalf of Licensee to third parties or (2) use of the
#   Software or any derivative of it for research with the final aim of
#   developing software products for sale or license to a third party or
#   (3) use of the Software or any derivative of it for research with the
#   final aim of developing non-software products for sale or license to a
#   third party, or (4) use of the Software to provide any service to an
#   external organisation for which payment is received. If you are
#   interested in using the Software commercially, please contact Isis
#   Innovation Limited ("Isis"), the technology transfer company of the
#   University, to negotiate a licence. Contact details are:
#   innovation@isis.ox.ac.uk quoting reference DE/1112.


Usage() {
    echo "Usage: siena_flirt <input1_fileroot> <input2_fileroot>"
    exit 1
}

if [ _$FSLDIR = _ ] ; then
    FSLDIR=/usr/local/fsl
    export FSLDIR
fi

[ "$2" = "" ] && Usage
[ `${FSLDIR}/bin/imtest $1` = 0 ] && Usage
[ `${FSLDIR}/bin/imtest $2` = 0 ] && Usage
A1=`${FSLDIR}/bin/remove_ext $1`
A2=`${FSLDIR}/bin/remove_ext $2`

# register using brains and skulls
${FSLDIR}/bin/pairreg ${A1}_brain ${A2}_brain ${A1}_brain_skull ${A2}_brain_skull ${A2}_to_${A1}.mat
${FSLDIR}/bin/pairreg ${A2}_brain ${A1}_brain ${A2}_brain_skull ${A1}_brain_skull ${A1}_to_${A2}.mat

# replace both transforms with "average" (reduces error level AND makes system symmetric)
F=${A1}_to_${A2}.mat
B=${A2}_to_${A1}.mat
${FSLDIR}/bin/convert_xfm -concat $B -omat tmp_${F}_then_${B} $F
${FSLDIR}/bin/avscale tmp_${F}_then_${B} ${A1} > tmp_${F}_then_${B}.avscale
${FSLDIR}/bin/extracttxt Backward tmp_${F}_then_${B}.avscale 4 1 > tmp_${F}_then_${B}_halfback
${FSLDIR}/bin/convert_xfm -concat tmp_${F}_then_${B}_halfback -omat $F $F
${FSLDIR}/bin/convert_xfm -inverse -omat $B $F
/bin/rm tmp_${F}_then_${B} tmp_${F}_then_${B}.avscale tmp_${F}_then_${B}_halfback

# replace the .mat matrix that takes 2->1 with one that takes 2->halfway and one that takes 1->halfway
${FSLDIR}/bin/avscale ${A2}_to_${A1}.mat ${A1}_brain > ${A2}_to_${A1}.mat_avscale
${FSLDIR}/bin/extracttxt Forward ${A2}_to_${A1}.mat_avscale 4 1 > ${A2}_halfwayto_${A1}.mat
${FSLDIR}/bin/extracttxt Backward ${A2}_to_${A1}.mat_avscale 4 1 > ${A1}_halfwayto_${A2}.mat

# produce picture for registration evaluation
${FSLDIR}/bin/flirt -out ${A1}_halfwayto_${A2} -applyxfm -init ${A1}_halfwayto_${A2}.mat -ref ${A1} -in ${A1}_brain
${FSLDIR}/bin/flirt -out ${A2}_halfwayto_${A1} -applyxfm -init ${A2}_halfwayto_${A1}.mat -ref ${A1} -in ${A2}_brain
${FSLDIR}/bin/slicer ${A1}_halfwayto_${A2} -s 1 -x 0.4 gr${A1}${A2}a.png -x 0.5 gr${A1}${A2}b.png -x 0.6 gr${A1}${A2}c.png -y 0.4 gr${A1}${A2}d.png -y 0.5 gr${A1}${A2}e.png -y 0.6 gr${A1}${A2}f.png -z 0.4 gr${A1}${A2}g.png -z 0.5 gr${A1}${A2}h.png -z 0.6 gr${A1}${A2}i.png
${FSLDIR}/bin/pngappend gr${A1}${A2}a.png + gr${A1}${A2}b.png + gr${A1}${A2}c.png + gr${A1}${A2}d.png + gr${A1}${A2}e.png + gr${A1}${A2}f.png + gr${A1}${A2}g.png + gr${A1}${A2}h.png + gr${A1}${A2}i.png gr${A1}${A2}j.gif
${FSLDIR}/bin/slicer ${A2}_halfwayto_${A1} -s 1 -x 0.4 gr${A1}${A2}a.png -x 0.5 gr${A1}${A2}b.png -x 0.6 gr${A1}${A2}c.png -y 0.4 gr${A1}${A2}d.png -y 0.5 gr${A1}${A2}e.png -y 0.6 gr${A1}${A2}f.png -z 0.4 gr${A1}${A2}g.png -z 0.5 gr${A1}${A2}h.png -z 0.6 gr${A1}${A2}i.png
${FSLDIR}/bin/pngappend gr${A1}${A2}a.png + gr${A1}${A2}b.png + gr${A1}${A2}c.png + gr${A1}${A2}d.png + gr${A1}${A2}e.png + gr${A1}${A2}f.png + gr${A1}${A2}g.png + gr${A1}${A2}h.png + gr${A1}${A2}i.png gr${A1}${A2}k.gif
${FSLDIR}/bin/whirlgif -o ${A1}_and_${A2}.gif -time 50 -loop 0 gr${A1}${A2}j.gif gr${A1}${A2}k.gif >/dev/null 2>&1 
/bin/rm gr${A1}${A2}?.??? `$FSLDIR/bin/imglob -extensions ${A2}_halfwayto_${A1}.* ${A1}_halfwayto_${A2}.*`

