#!/bin/sh

#   first_roi_slicesdir - script to view slicesdir on a region of interest
#   defined by a set of label images (e.g. output of FIRST). A set of 
#   temporary roi images are created, slicesdir is then run on those.
#
#   Brian Patenaude and Matthew Webster, FMRIB Image Analysis Group
#
#   Copyright (C) 2006-2010 University of Oxford
#
#   Part of FSL - FMRIB's Software Library
#   http://www.fmrib.ox.ac.uk/fsl
#   fsl@fmrib.ox.ac.uk
#   
#   Developed at FMRIB (Oxford Centre for Functional Magnetic Resonance
#   Imaging of the Brain), Department of Clinical Neurology, Oxford
#   University, Oxford, UK
#   
#   
#   LICENCE
#   
#   FMRIB Software Library, Release 4.0 (c) 2007, The University of
#   Oxford (the "Software")
#   
#   The Software remains the property of the University of Oxford ("the
#   University").
#   
#   The Software is distributed "AS IS" under this Licence solely for
#   non-commercial use in the hope that it will be useful, but in order
#   that the University as a charitable foundation protects its assets for
#   the benefit of its educational and research purposes, the University
#   makes clear that no condition is made or to be implied, nor is any
#   warranty given or to be implied, as to the accuracy of the Software,
#   or that it will be suitable for any particular purpose or for use
#   under any specific conditions. Furthermore, the University disclaims
#   all responsibility for the use which is made of the Software. It
#   further disclaims any liability for the outcomes arising from using
#   the Software.
#   
#   The Licensee agrees to indemnify the University and hold the
#   University harmless from and against any and all claims, damages and
#   liabilities asserted by third parties (including claims for
#   negligence) which arise directly or indirectly from the use of the
#   Software or the sale of any products based on the Software.
#   
#   No part of the Software may be reproduced, modified, transmitted or
#   transferred in any form or by any means, electronic or mechanical,
#   without the express permission of the University. The permission of
#   the University is not required if the said reproduction, modification,
#   transmission or transference is done without financial return, the
#   conditions of this Licence are imposed upon the receiver of the
#   product, and all original and amended source code is included in any
#   transmitted product. You may be held legally responsible for any
#   copyright infringement that is caused or encouraged by your failure to
#   abide by these terms and conditions.
#   
#   You are not permitted under this Licence to use this Software
#   commercially. Use for which any financial return is received shall be
#   defined as commercial use, and includes (1) integration of all or part
#   of the source code or the Software into a product for sale or license
#   by or on behalf of Licensee to third parties or (2) use of the
#   Software or any derivative of it for research with the final aim of
#   developing software products for sale or license to a third party or
#   (3) use of the Software or any derivative of it for research with the
#   final aim of developing non-software products for sale or license to a
#   third party, or (4) use of the Software to provide any service to an
#   external organisation for which payment is received. If you are
#   interested in using the Software commercially, please contact Isis
#   Innovation Limited ("Isis"), the technology transfer company of the
#   University, to negotiate a licence. Contact details are:
#   innovation@isis.ox.ac.uk quoting reference DE/1112.

Usage() {
    echo ""
    echo "Usage:   first_roi_slicesdir  <input_t1_images> <input_label_images>"
    echo ""
    echo "e.g.:  first_roi_slicesdir *_t1.nii.gz *_L_Hipp_first.nii.gz "
    echo ""
    exit
}

[ "${1}_" = "_"  ] && Usage

num=$#
echo "total number of image: " $num
num=`echo "${num}/2 " | bc`
echo "number of image pairs: " $num

#this loop creates the paired list  
i=1;
while [ $i -le ${num} ] ; do 

    pout=`echo $@ | awk '{ print $'$i' }'`
    
    imind=`echo ${i} + ${num} | bc`
    imlb=`echo $@ | awk '{ print $'$imind' }'`
      imlbout=`echo $imlb | awk -F / '{ print $NF }'`
      imlbout=`remove_ext $imlbout `

    roi=`${FSLDIR}/bin/fslstats $imlb -w` 

    xmin=`echo $roi | awk '{ print $1 }'`
    xsize=`echo $roi | awk '{ print $2 }'`
    xmin=`echo $xmin - 10 | bc`
    xsize=`echo $xsize + 20 | bc`

    
    ymin=`echo $roi | awk '{ print $3 }'`
    ysize=`echo $roi | awk '{ print $4 }'`
    ymin=`echo $ymin - 10 | bc`
    ysize=`echo $ysize + 20 | bc`
 
    zmin=`echo $roi | awk '{ print $5 }'`
    zsize=`echo $roi | awk '{ print $6 }'`
    zmin=`echo $zmin - 10 | bc`
    zsize=`echo $zsize + 20 | bc`

    roi="${xmin} $xsize $ymin $ysize $zmin $zsize 0 1"

    pout=`remove_ext $pout`
    imlb=`remove_ext $imlb`
    
    pout2=`echo $pout | awk -F / '{ print $NF }'`
    pout2=`remove_ext $pout2`
    echo $i $pout2

    ${FSLDIR}/bin/fslroi $pout ${pout2}_t1grot${i} $roi
    ${FSLDIR}/bin/fslroi $imlb ${imlbout}lbgrot${i} $roi
    pairlist=${pairlist}" "${pout2}_t1grot${i}" "${imlbout}lbgrot${i}
   
    i=$((i+1)); 
done

echo "run slicesdir"
${FSLDIR}/bin/slicesdir -o -e -1 ${pairlist}

#remove tmeporrary images

echo "removing files..."
for i in $pairlist; do 
    echo $i; 
   ${FSLDIR}/bin/imrm $i; 
done


