#!/bin/sh

#   surface_fdr - runs FDR correction on a FIRST surface (from vertex analysis)
#
#   Mark Jenkinson, FMRIB Image Analysis Group
#
#   Copyright (C) 2008-2009 University of Oxford
#
#   Part of FSL - FMRIB's Software Library
#   http://www.fmrib.ox.ac.uk/fsl
#   fsl@fmrib.ox.ac.uk
#   
#   Developed at FMRIB (Oxford Centre for Functional Magnetic Resonance
#   Imaging of the Brain), Department of Clinical Neurology, Oxford
#   University, Oxford, UK
#   
#   
#   LICENCE
#   
#   FMRIB Software Library, Release 4.0 (c) 2007, The University of
#   Oxford (the "Software")
#   
#   The Software remains the property of the University of Oxford ("the
#   University").
#   
#   The Software is distributed "AS IS" under this Licence solely for
#   non-commercial use in the hope that it will be useful, but in order
#   that the University as a charitable foundation protects its assets for
#   the benefit of its educational and research purposes, the University
#   makes clear that no condition is made or to be implied, nor is any
#   warranty given or to be implied, as to the accuracy of the Software,
#   or that it will be suitable for any particular purpose or for use
#   under any specific conditions. Furthermore, the University disclaims
#   all responsibility for the use which is made of the Software. It
#   further disclaims any liability for the outcomes arising from using
#   the Software.
#   
#   The Licensee agrees to indemnify the University and hold the
#   University harmless from and against any and all claims, damages and
#   liabilities asserted by third parties (including claims for
#   negligence) which arise directly or indirectly from the use of the
#   Software or the sale of any products based on the Software.
#   
#   No part of the Software may be reproduced, modified, transmitted or
#   transferred in any form or by any means, electronic or mechanical,
#   without the express permission of the University. The permission of
#   the University is not required if the said reproduction, modification,
#   transmission or transference is done without financial return, the
#   conditions of this Licence are imposed upon the receiver of the
#   product, and all original and amended source code is included in any
#   transmitted product. You may be held legally responsible for any
#   copyright infringement that is caused or encouraged by your failure to
#   abide by these terms and conditions.
#   
#   You are not permitted under this Licence to use this Software
#   commercially. Use for which any financial return is received shall be
#   defined as commercial use, and includes (1) integration of all or part
#   of the source code or the Software into a product for sale or license
#   by or on behalf of Licensee to third parties or (2) use of the
#   Software or any derivative of it for research with the final aim of
#   developing software products for sale or license to a third party or
#   (3) use of the Software or any derivative of it for research with the
#   final aim of developing non-software products for sale or license to a
#   third party, or (4) use of the Software to provide any service to an
#   external organisation for which payment is received. If you are
#   interested in using the Software commercially, please contact Isis
#   Innovation Limited ("Isis"), the technology transfer company of the
#   University, to negotiate a licence. Contact details are:
#   innovation@isis.ox.ac.uk quoting reference DE/1112.


if [ $# -lt 1 ] ; then
  echo "Usage: `basename $0` <input_vtk>"
  echo "         where input_vtk is the vertex analysis vtk output"
  echo "         Outputs are *_pvals.vtk  *_Fthresh.vtk and some nifti images"
  echo "          (using the input vtk filename as the basename for output files)"
#  echo "       For FSL4.1.2 or before:"
#  echo "       `basename $0` <input vtk> <dof> <dof2>"
#  echo "         For the second usage the two Degrees Of Freedom for the" 
#  echo "         F-stats are specified directly."
#  echo "         (NB: these are stored in the vtk file for FSL4.1.3 and later)"
  exit 1
fi

infile=`echo $1 | sed 's/.vtk$//'`;

if [ $# -ge 3 ] ; then
    dof=$2
    dof2=$3
elif [ $# -eq 2 ] ; then
    txtfile=$2
    dof=`cat ${txtfile} | grep -i pillai | head -1 | awk '{ print $5 }'`;
    dof2=`cat ${txtfile} | grep -i pillai | head -1 | awk '{ print $6 }'`;
    echo "Degrees of freedom are: $dof $dof2"
fi
if [ $# -ge 2 ] ; then
  dofopts="--dof=$dof --dof2=$dof2"
else
  dofopts=""
fi

$FSLDIR/bin/run_mesh_utils -m ${infile}.vtk -o ${infile}_Fvals --doScalarsToVolume
$FSLDIR/bin/run_mesh_utils -m ${infile}.vtk -o ${infile}_pvals.vtk --doFtoP $dofopts
$FSLDIR/bin/run_mesh_utils -m ${infile}_pvals.vtk -o ${infile}_pvals --doScalarsToVolume
thr=`$FSLDIR/bin/fdr -i ${infile}_pvals -q 0.05 | grep -v '^ *[A-Za-z]'`;
echo "FDR threshold is $thr"
$FSLDIR/bin/fslmaths ${infile}_pvals -uthr $thr -bin ${infile}_fdrmask
$FSLDIR/bin/fslmaths ${infile}_pvals -mas ${infile}_fdrmask ${infile}_pthresh
$FSLDIR/bin/fslmaths ${infile}_Fvals -mas ${infile}_fdrmask ${infile}_Fthresh
$FSLDIR/bin/run_mesh_utils -m ${infile}.vtk -i ${infile}_Fthresh -o ${infile}_Fthresh.vtk --doVolumeToScalars

