#!/bin/sh

#   easythresh - quick method of getting stats outside of feat
#
#   Stephen Smith and Mark Jenkinson, FMRIB Image Analysis Group
#
#   Copyright (C) 1999-2007 University of Oxford
#
#   Part of FSL - FMRIB's Software Library
#   http://www.fmrib.ox.ac.uk/fsl
#   fsl@fmrib.ox.ac.uk
#   
#   Developed at FMRIB (Oxford Centre for Functional Magnetic Resonance
#   Imaging of the Brain), Department of Clinical Neurology, Oxford
#   University, Oxford, UK
#   
#   
#   LICENCE
#   
#   FMRIB Software Library, Release 4.0 (c) 2007, The University of
#   Oxford (the "Software")
#   
#   The Software remains the property of the University of Oxford ("the
#   University").
#   
#   The Software is distributed "AS IS" under this Licence solely for
#   non-commercial use in the hope that it will be useful, but in order
#   that the University as a charitable foundation protects its assets for
#   the benefit of its educational and research purposes, the University
#   makes clear that no condition is made or to be implied, nor is any
#   warranty given or to be implied, as to the accuracy of the Software,
#   or that it will be suitable for any particular purpose or for use
#   under any specific conditions. Furthermore, the University disclaims
#   all responsibility for the use which is made of the Software. It
#   further disclaims any liability for the outcomes arising from using
#   the Software.
#   
#   The Licensee agrees to indemnify the University and hold the
#   University harmless from and against any and all claims, damages and
#   liabilities asserted by third parties (including claims for
#   negligence) which arise directly or indirectly from the use of the
#   Software or the sale of any products based on the Software.
#   
#   No part of the Software may be reproduced, modified, transmitted or
#   transferred in any form or by any means, electronic or mechanical,
#   without the express permission of the University. The permission of
#   the University is not required if the said reproduction, modification,
#   transmission or transference is done without financial return, the
#   conditions of this Licence are imposed upon the receiver of the
#   product, and all original and amended source code is included in any
#   transmitted product. You may be held legally responsible for any
#   copyright infringement that is caused or encouraged by your failure to
#   abide by these terms and conditions.
#   
#   You are not permitted under this Licence to use this Software
#   commercially. Use for which any financial return is received shall be
#   defined as commercial use, and includes (1) integration of all or part
#   of the source code or the Software into a product for sale or license
#   by or on behalf of Licensee to third parties or (2) use of the
#   Software or any derivative of it for research with the final aim of
#   developing software products for sale or license to a third party or
#   (3) use of the Software or any derivative of it for research with the
#   final aim of developing non-software products for sale or license to a
#   third party, or (4) use of the Software to provide any service to an
#   external organisation for which payment is received. If you are
#   interested in using the Software commercially, please contact Isis
#   Innovation Limited ("Isis"), the technology transfer company of the
#   University, to negotiate a licence. Contact details are:
#   innovation@isis.ox.ac.uk quoting reference DE/1112.

Usage() {
    echo ""
    echo "Usage: easythresh <raw_zstat> <brain_mask> <cluster_z_thresh> <cluster_prob_thresh> <background_image> <output_root> [--mm]"
    echo "e.g.:  easythresh stats/zstat1 mask 2.3 0.01 example_func grot"
    echo ""
    echo "Or:    easythresh <stat> <stat_thresh> <background_image> <output_root>"
    echo "e.g.:  easythresh stats/zstat1 2.3 example_func grot"
    echo ""
    exit 1
}

if [ "$5" = "" ] ; then
    [ "$4" = "" ] && Usage
    MAX=`${FSLDIR}/bin/fslstats $1 -R | awk '{print $2}'`
    ${FSLDIR}/bin/overlay 1 0 $3 -a $1 $2 $MAX rendered_$4
    ${FSLDIR}/bin/slicer rendered_$4 -A 750 rendered_$4.png
    exit
fi

[ "$6" = "" ] && Usage

# estimate image smoothness
SM=`${FSLDIR}/bin/smoothest -z $1 -m $2`
DLH=`echo $SM | awk '{print $2}'`
VOLUME=`echo $SM | awk '{print $4}'`
RESELS=`echo $SM | awk '{print $6}'`
#echo "$DLH $VOLUME $RESELS"

# run clustering after fixing stats header for talspace
${FSLDIR}/bin/fslmaths $1 -mas $2 thresh_$6
${FSLDIR}/bin/fslcpgeom $5 thresh_$6
${FSLDIR}/bin/cluster -i thresh_$6 -t $3 -p $4 --volume=$VOLUME -d $DLH -o cluster_mask_$6 --othresh=thresh_$6 $7 > cluster_$6.txt

# colour rendering
MAX=`${FSLDIR}/bin/fslstats thresh_$6 -R | awk '{print $2}'`
${FSLDIR}/bin/overlay 1 0 $5 -a thresh_$6 $3 $MAX rendered_thresh_$6
${FSLDIR}/bin/slicer rendered_thresh_$6 -A 750 rendered_thresh_$6.png

