#!/bin/sh

#   fslerrorreport - display lots of information that is to be sent
#                    to the FSL list when any questions are asked concerning
#                    possible errors
#
#   Mark Jenkinson, FMRIB Image Analysis Group
#
#   Copyright (C) 2004 University of Oxford
#
#   Part of FSL - FMRIB's Software Library
#   http://www.fmrib.ox.ac.uk/fsl
#   fsl@fmrib.ox.ac.uk
#   
#   Developed at FMRIB (Oxford Centre for Functional Magnetic Resonance
#   Imaging of the Brain), Department of Clinical Neurology, Oxford
#   University, Oxford, UK
#   
#   
#   LICENCE
#   
#   FMRIB Software Library, Release 4.0 (c) 2007, The University of
#   Oxford (the "Software")
#   
#   The Software remains the property of the University of Oxford ("the
#   University").
#   
#   The Software is distributed "AS IS" under this Licence solely for
#   non-commercial use in the hope that it will be useful, but in order
#   that the University as a charitable foundation protects its assets for
#   the benefit of its educational and research purposes, the University
#   makes clear that no condition is made or to be implied, nor is any
#   warranty given or to be implied, as to the accuracy of the Software,
#   or that it will be suitable for any particular purpose or for use
#   under any specific conditions. Furthermore, the University disclaims
#   all responsibility for the use which is made of the Software. It
#   further disclaims any liability for the outcomes arising from using
#   the Software.
#   
#   The Licensee agrees to indemnify the University and hold the
#   University harmless from and against any and all claims, damages and
#   liabilities asserted by third parties (including claims for
#   negligence) which arise directly or indirectly from the use of the
#   Software or the sale of any products based on the Software.
#   
#   No part of the Software may be reproduced, modified, transmitted or
#   transferred in any form or by any means, electronic or mechanical,
#   without the express permission of the University. The permission of
#   the University is not required if the said reproduction, modification,
#   transmission or transference is done without financial return, the
#   conditions of this Licence are imposed upon the receiver of the
#   product, and all original and amended source code is included in any
#   transmitted product. You may be held legally responsible for any
#   copyright infringement that is caused or encouraged by your failure to
#   abide by these terms and conditions.
#   
#   You are not permitted under this Licence to use this Software
#   commercially. Use for which any financial return is received shall be
#   defined as commercial use, and includes (1) integration of all or part
#   of the source code or the Software into a product for sale or license
#   by or on behalf of Licensee to third parties or (2) use of the
#   Software or any derivative of it for research with the final aim of
#   developing software products for sale or license to a third party or
#   (3) use of the Software or any derivative of it for research with the
#   final aim of developing non-software products for sale or license to a
#   third party, or (4) use of the Software to provide any service to an
#   external organisation for which payment is received. If you are
#   interested in using the Software commercially, please contact Isis
#   Innovation Limited ("Isis"), the technology transfer company of the
#   University, to negotiate a licence. Contact details are:
#   innovation@isis.ox.ac.uk quoting reference DE/1112.

filename=`$FSLDIR/bin/tmpnam`
if [ "X$filename" = X ] ; then
  filename=$HOME/fslerrorreport.txt
fi

echo " " > $filename

echo "######################################################################" >> $filename
echo "#### MACHINE INFORMATION" >> $filename
echo "######################################################################" >> $filename
echo " " >> $filename

echo "Uname:" >> $filename
uname >> $filename
echo " " >> $filename
echo "df:" >> $filename
df . >> $filename
echo " " >> $filename
echo "quota:" >> $filename
quota >> $filename

echo " " >> $filename
echo "Memory and Swap info:" >> $filename
if [ -f /proc/meminfo ] ; then
  cat /proc/meminfo >> $filename ;
else
  vm_stat >> $filename
  vmstat -s >> $filename
fi

echo " " >> $filename
echo "######################################################################" >> $filename
echo "#### ENVIRONMENT INFORMATION" >> $filename
echo "######################################################################" >> $filename
echo " " >> $filename

env | grep FSL >> $filename
echo " " >> $filename
env | grep PATH >> $filename
env | grep LD_LIBRARY_PATH >> $filename

echo " " >> $filename
echo "######################################################################" >> $filename
echo "#### DIRECTORY INFORMATION" >> $filename
echo "######################################################################" >> $filename
echo " " >> $filename

echo "PWD:" >> $filename
pwd >> $filename
echo " " >> $filename
ls -la >> $filename

imgname=""
featname=""
fdtname=""
icaname=""

if [ $# -ge 1 ] ; then
    imgname=$1
else
    imgname=`pwd`;
fi


if [ `echo $imgname | grep \.feat | wc -l` -ge 1 ] ; then
    featname=$imgname
    imgname=""
fi
if [ `echo $imgname | grep \.gfeat | wc -l` -ge 1 ] ; then
    featname=$imgname
    imgname=""
fi
if [ `echo $imgname | grep \.bedpost | wc -l` -ge 1 ] ; then
    fdtname=$imgname
    imgname=""
fi
if [ `echo $imgname | grep \.ica | wc -l` -ge 1 ] ; then
    icaname=$imgname
    imgname=""
fi



if [ X$imgname != X ] ; then
    echo " " >> $filename
    echo "######################################################################" >> $filename
    echo "#### IMAGE INFORMATION" >> $filename
    echo "######################################################################" >> $filename
    echo " " >> $filename
    $FSLDIR/bin/fslhd $imgname >> $filename
fi

if [ X$featname != X ] ; then
    echo " " >> $filename
    echo "######################################################################" >> $filename
    echo "#### FEAT INFORMATION" >> $filename
    echo "######################################################################" >> $filename
    echo " " >> $filename
    echo "Report log:" >> $filename
    cat $featname/report.log >> $filename
    
    echo " " >> $filename
    echo "######################################################################" >> $filename	
    echo " " >> $filename
    echo "Design Matrix:" >> $filename
    cat $featname/design.mat >> $filename
    
    if [ -f $featname/design.grp ] ; then
	echo " " >> $filename
	echo "######################################################################" >> $filename	
	echo " " >> $filename
	echo "Group Design Matrix:" >> $filename
	cat $featname/design.grp >> $filename
    fi
    
    echo " " >> $filename
    echo "######################################################################" >> $filename	
    echo " " >> $filename
    echo "Contrast Matrix:" >> $filename
    cat $featname/design.con >> $filename
    
    echo " " >> $filename
    echo "######################################################################" >> $filename	
    echo " " >> $filename
    echo "FTS Matrix:" >> $filename
    cat $featname/design.fts >> $filename
    
    echo " " >> $filename
    echo "######################################################################" >> $filename
    echo "#### Main directory:" >> $filename
    echo " " >> $filename
    ls -la $featname >> $filename
    
    echo " " >> $filename
    echo "######################################################################" >> $filename
    echo "#### Stats directory:" >> $filename
    echo " " >> $filename
    ls -la $featname/stats >> $filename
    
    echo " " >> $filename
    echo "######################################################################" >> $filename
    echo "#### Reg directory:" >> $filename
    echo " " >> $filename
    ls -la $featname/reg >> $filename
    
fi

if [ X$fdtname != X ] ; then
    echo " " >> $filename
    echo "######################################################################" >> $filename
    echo "#### FDT INFORMATION" >> $filename
    echo "######################################################################" >> $filename
    echo " " >> $filename
    echo "######################################################################" >> $filename
    echo "#### Main directory:" >> $filename
    echo " " >> $filename
    ls -la $fdtname >> $filename
    
    echo " " >> $filename
    $FSLDIR/bin/bedpost_datacheck $fdtname >> $filename
fi

if [ X$icaname != X ] ; then
    echo " " >> $filename
    echo "######################################################################" >> $filename
    echo "#### MELODIC INFORMATION" >> $filename
    echo "######################################################################" >> $filename
    echo " " >> $filename
    echo "Log files:" >> $filename
    cat $icaname/*.log >> $filename
    
    echo " " >> $filename
    echo "######################################################################" >> $filename
    echo "#### Main directory:" >> $filename
    echo " " >> $filename
    ls -la $icaname >> $filename
    
fi

cat $filename

gzip -9 $filename

echo " "
echo "This error report is saved in the file: ${filename}.gz"
echo " "
