#!/bin/sh

#   perfusion_subtract - tag-control subtraction with half-TR shifting and no decimation
#
#   Stephen Smith, Karla Miller, Mark Woolrich and Matthew Webster, FMRIB
#
#   Copyright (C) 2006-2009 University of Oxford
#
#   Part of FSL - FMRIB's Software Library
#   http://www.fmrib.ox.ac.uk/fsl
#   fsl@fmrib.ox.ac.uk
#   
#   Developed at FMRIB (Oxford Centre for Functional Magnetic Resonance
#   Imaging of the Brain), Department of Clinical Neurology, Oxford
#   University, Oxford, UK
#   
#   
#   LICENCE
#   
#   FMRIB Software Library, Release 4.0 (c) 2007, The University of
#   Oxford (the "Software")
#   
#   The Software remains the property of the University of Oxford ("the
#   University").
#   
#   The Software is distributed "AS IS" under this Licence solely for
#   non-commercial use in the hope that it will be useful, but in order
#   that the University as a charitable foundation protects its assets for
#   the benefit of its educational and research purposes, the University
#   makes clear that no condition is made or to be implied, nor is any
#   warranty given or to be implied, as to the accuracy of the Software,
#   or that it will be suitable for any particular purpose or for use
#   under any specific conditions. Furthermore, the University disclaims
#   all responsibility for the use which is made of the Software. It
#   further disclaims any liability for the outcomes arising from using
#   the Software.
#   
#   The Licensee agrees to indemnify the University and hold the
#   University harmless from and against any and all claims, damages and
#   liabilities asserted by third parties (including claims for
#   negligence) which arise directly or indirectly from the use of the
#   Software or the sale of any products based on the Software.
#   
#   No part of the Software may be reproduced, modified, transmitted or
#   transferred in any form or by any means, electronic or mechanical,
#   without the express permission of the University. The permission of
#   the University is not required if the said reproduction, modification,
#   transmission or transference is done without financial return, the
#   conditions of this Licence are imposed upon the receiver of the
#   product, and all original and amended source code is included in any
#   transmitted product. You may be held legally responsible for any
#   copyright infringement that is caused or encouraged by your failure to
#   abide by these terms and conditions.
#   
#   You are not permitted under this Licence to use this Software
#   commercially. Use for which any financial return is received shall be
#   defined as commercial use, and includes (1) integration of all or part
#   of the source code or the Software into a product for sale or license
#   by or on behalf of Licensee to third parties or (2) use of the
#   Software or any derivative of it for research with the final aim of
#   developing software products for sale or license to a third party or
#   (3) use of the Software or any derivative of it for research with the
#   final aim of developing non-software products for sale or license to a
#   third party, or (4) use of the Software to provide any service to an
#   external organisation for which payment is received. If you are
#   interested in using the Software commercially, please contact Isis
#   Innovation Limited ("Isis"), the technology transfer company of the
#   University, to negotiate a licence. Contact details are:
#   innovation@isis.ox.ac.uk quoting reference DE/1112.

Usage() {
    echo ""
    echo "Usage: perfusion_subtract <4D_input> <4D_output> [-c]"
    echo "-c : first timepoint is control instead of tag (default is tag first)"
    echo ""
    exit 1
}

[ "$2" = "" ] && Usage
IN=`$FSLDIR/bin/remove_ext $1`
OUT=`$FSLDIR/bin/remove_ext $2`
shift 2

tmpbase=`$FSLDIR/bin/tmpnam`
invert=""
demean="-add ${tmpbase}_asl_subtract/mean"
while [ _$1 != _ ] ; do
    if [ $1 = -c ] ; then
	invert="-mul -1.0"
	shift
    elif [ $1 = -m ] ; then
	demean=""
	shift
    else
        Usage
    fi
done

mkdir ${tmpbase}_asl_subtract

${FSLDIR}/bin/fslmaths $IN -Tmean ${tmpbase}_asl_subtract/mean
${FSLDIR}/bin/fslsplit $IN ${tmpbase}_asl_subtract/vol

OLDPWD=`pwd`
cd ${tmpbase}_asl_subtract

${FSLDIR}/bin/fslmerge -t even `${FSLDIR}/bin/imglob vol*[02468].*`
${FSLDIR}/bin/fslmerge -t odd  `${FSLDIR}/bin/imglob vol*[13579].*`

if [ `${FSLDIR}/bin/fslnvols even` != `${FSLDIR}/bin/fslnvols odd` ] ; then
    echo "Warning - odd number of timepoints in input data - will ignore last timepoint"
    ${FSLDIR}/bin/fslroi even even 0 `${FSLDIR}/bin/fslnvols odd`
fi

${FSLDIR}/bin/slicetimer -i odd  -o odd_earlier  --tglobal=0.75
${FSLDIR}/bin/slicetimer -i odd  -o odd_later    --tglobal=0.25
${FSLDIR}/bin/slicetimer -i even -o even_earlier --tglobal=0.75
${FSLDIR}/bin/slicetimer -i even -o even_later   --tglobal=1.25
${FSLDIR}/bin/fslmaths odd_later   -sub even_earlier even_to_odd
${FSLDIR}/bin/fslmaths odd_earlier -sub even_later   odd_to_even
${FSLDIR}/bin/fslsplit even_to_odd e_
${FSLDIR}/bin/fslsplit odd_to_even o_

la=`${FSLDIR}/bin/imglob -extension [eo]_*`
lb=`ls -1 $la | sort -t _ -k 2`
${FSLDIR}/bin/fslmerge -t output $lb

cd $OLDPWD

${FSLDIR}/bin/fslmaths ${tmpbase}_asl_subtract/output $invert $demean $OUT

/bin/rm -rf ${tmpbase}*

exit 0

################################################################################

SINC

0   1   2   3   4   5   6
    c       c       c
t       t       t       t

  c       c       c       c    odd_later       \__subtract to make even_to_odd
  t       t       t       t    even _earlier   /

      c       c       c        odd_earlier     \__subtract to make odd_to_even
      t       t       t        even_later      /

################################################################################

