#!/bin/sh

#   renderhighres - put activation results on the highres image
#
#   Stephen Smith and Mark Jenkinson, FMRIB Image Analysis Group
#
#   Copyright (C) 1999-2008 University of Oxford
#
#   Part of FSL - FMRIB's Software Library
#   http://www.fmrib.ox.ac.uk/fsl
#   fsl@fmrib.ox.ac.uk
#   
#   Developed at FMRIB (Oxford Centre for Functional Magnetic Resonance
#   Imaging of the Brain), Department of Clinical Neurology, Oxford
#   University, Oxford, UK
#   
#   
#   LICENCE
#   
#   FMRIB Software Library, Release 4.0 (c) 2007, The University of
#   Oxford (the "Software")
#   
#   The Software remains the property of the University of Oxford ("the
#   University").
#   
#   The Software is distributed "AS IS" under this Licence solely for
#   non-commercial use in the hope that it will be useful, but in order
#   that the University as a charitable foundation protects its assets for
#   the benefit of its educational and research purposes, the University
#   makes clear that no condition is made or to be implied, nor is any
#   warranty given or to be implied, as to the accuracy of the Software,
#   or that it will be suitable for any particular purpose or for use
#   under any specific conditions. Furthermore, the University disclaims
#   all responsibility for the use which is made of the Software. It
#   further disclaims any liability for the outcomes arising from using
#   the Software.
#   
#   The Licensee agrees to indemnify the University and hold the
#   University harmless from and against any and all claims, damages and
#   liabilities asserted by third parties (including claims for
#   negligence) which arise directly or indirectly from the use of the
#   Software or the sale of any products based on the Software.
#   
#   No part of the Software may be reproduced, modified, transmitted or
#   transferred in any form or by any means, electronic or mechanical,
#   without the express permission of the University. The permission of
#   the University is not required if the said reproduction, modification,
#   transmission or transference is done without financial return, the
#   conditions of this Licence are imposed upon the receiver of the
#   product, and all original and amended source code is included in any
#   transmitted product. You may be held legally responsible for any
#   copyright infringement that is caused or encouraged by your failure to
#   abide by these terms and conditions.
#   
#   You are not permitted under this Licence to use this Software
#   commercially. Use for which any financial return is received shall be
#   defined as commercial use, and includes (1) integration of all or part
#   of the source code or the Software into a product for sale or license
#   by or on behalf of Licensee to third parties or (2) use of the
#   Software or any derivative of it for research with the final aim of
#   developing software products for sale or license to a third party or
#   (3) use of the Software or any derivative of it for research with the
#   final aim of developing non-software products for sale or license to a
#   third party, or (4) use of the Software to provide any service to an
#   external organisation for which payment is received. If you are
#   interested in using the Software commercially, please contact Isis
#   Innovation Limited ("Isis"), the technology transfer company of the
#   University, to negotiate a licence. Contact details are:
#   innovation@isis.ox.ac.uk quoting reference DE/1112.


Usage() {
    echo "Usage: renderhighres <feat_directory> <space> <background> <autothresh> [minZ maxZ]"
    echo "<space>: either highres or standard"
    echo "<background>: either highres or standard"
    echo "<autothresh>: either 0 or 1 (colour-code using existing post-threshold range? If 0 then minZ and maxZ are used)"
    echo ""
    exit 1
}

[ "$4" = "" ] && Usage
[ "$4" = "0" -a "$6" = "" ] && Usage

cd $1

space=$2
background=$3
autothresh=$4

if [ `${FSLDIR}/bin/imtest reg/$space` != 1 ] ; then
    echo "Can't use $space for output space - doesn't exist in the FEAT registration output"
    exit 1
fi

if [ `${FSLDIR}/bin/imtest reg/$background` != 1 ] ; then
    echo "Can't use $background for background image - doesn't exist in the FEAT registration output"
    exit 1
fi

/bin/rm -rf hr
mkdir hr
cd hr

if [ $background != $space ] ; then
    if [ `${FSLDIR}/bin/imtest ../reg/highres2standard_warp` = 1 ] ; then
	if [ $background = standard ] ; then
	    ${FSLDIR}/bin/invfeatreg ..
	    ${FSLDIR}/bin/applywarp --ref=../reg/highres --in=../reg/standard --out=background --warp=../reg/highres2standard_warp_inv --interp=sinc
	else
	    ${FSLDIR}/bin/applywarp --ref=../reg/standard --in=../reg/highres --out=background --warp=../reg/highres2standard_warp --interp=sinc
	fi
    else
	${FSLDIR}/bin/flirt -in ../reg/$background -out background -ref ../reg/$space -applyxfm -init ../reg/${background}2${space}.mat -interp sinc -sincwidth 7 -sincwindow hanning
    fi
else
    ${FSLDIR}/bin/imcp ../reg/$space background
fi

for f in `cd .. ; ${FSLDIR}/bin/imglob thresh_*.*` ; do
    f=`${FSLDIR}/bin/remove_ext $f`

    if [ $space = standard -a `${FSLDIR}/bin/imtest ../reg/highres2standard_warp` = 1 ] ; then
	${FSLDIR}/bin/applywarp --ref=../reg/standard --in=../$f --out=$f --warp=../reg/highres2standard_warp --premat=../reg/example_func2highres.mat --interp=sinc
    else
	${FSLDIR}/bin/flirt -in ../$f -out $f -ref ../reg/$space -applyxfm -init ../reg/example_func2${space}.mat -interp sinc -sincwidth 7 -sincwindow hanning
    fi

    if [ $autothresh = 1 ] ; then
	minZ=`${FSLDIR}/bin/fslstats ../$f -l 0.01 -R | awk '{print $1}'`
	maxZ=`${FSLDIR}/bin/fslstats ../$f         -R | awk '{print $2}'`
    else
	minZ=$5
	maxZ=$6
    fi

    ${FSLDIR}/bin/overlay 1 1 background -a $f $minZ $maxZ rendered_$f
    ${FSLDIR}/bin/slicer rendered_$f -S 2 900 rendered_${f}.png
done

