#!/bin/sh

#   filmbabescript
#
#   Mark Woolrich, FMRIB Image Analysis Group
#
#   Copyright (C) 2002-2004 University of Oxford
#
#   Part of FSL - FMRIB's Software Library
#   http://www.fmrib.ox.ac.uk/fsl
#   fsl@fmrib.ox.ac.uk
#   
#   Developed at FMRIB (Oxford Centre for Functional Magnetic Resonance
#   Imaging of the Brain), Department of Clinical Neurology, Oxford
#   University, Oxford, UK
#   
#   
#   LICENCE
#   
#   FMRIB Software Library, Release 4.0 (c) 2007, The University of
#   Oxford (the "Software")
#   
#   The Software remains the property of the University of Oxford ("the
#   University").
#   
#   The Software is distributed "AS IS" under this Licence solely for
#   non-commercial use in the hope that it will be useful, but in order
#   that the University as a charitable foundation protects its assets for
#   the benefit of its educational and research purposes, the University
#   makes clear that no condition is made or to be implied, nor is any
#   warranty given or to be implied, as to the accuracy of the Software,
#   or that it will be suitable for any particular purpose or for use
#   under any specific conditions. Furthermore, the University disclaims
#   all responsibility for the use which is made of the Software. It
#   further disclaims any liability for the outcomes arising from using
#   the Software.
#   
#   The Licensee agrees to indemnify the University and hold the
#   University harmless from and against any and all claims, damages and
#   liabilities asserted by third parties (including claims for
#   negligence) which arise directly or indirectly from the use of the
#   Software or the sale of any products based on the Software.
#   
#   No part of the Software may be reproduced, modified, transmitted or
#   transferred in any form or by any means, electronic or mechanical,
#   without the express permission of the University. The permission of
#   the University is not required if the said reproduction, modification,
#   transmission or transference is done without financial return, the
#   conditions of this Licence are imposed upon the receiver of the
#   product, and all original and amended source code is included in any
#   transmitted product. You may be held legally responsible for any
#   copyright infringement that is caused or encouraged by your failure to
#   abide by these terms and conditions.
#   
#   You are not permitted under this Licence to use this Software
#   commercially. Use for which any financial return is received shall be
#   defined as commercial use, and includes (1) integration of all or part
#   of the source code or the Software into a product for sale or license
#   by or on behalf of Licensee to third parties or (2) use of the
#   Software or any derivative of it for research with the final aim of
#   developing software products for sale or license to a third party or
#   (3) use of the Software or any derivative of it for research with the
#   final aim of developing non-software products for sale or license to a
#   third party, or (4) use of the Software to provide any service to an
#   external organisation for which payment is received. If you are
#   interested in using the Software commercially, please contact Isis
#   Innovation Limited ("Isis"), the technology transfer company of the
#   University, to negotiate a licence. Contact details are:
#   innovation@isis.ox.ac.uk quoting reference DE/1112.

# $1 is feat directory
#
# e.g.featdir=/home/fs3/steve/data/fmri_test/heatpain+vis_1352/epi3.4_SDfixed_junkscut_FLOBS.feat

if [ $# -ne 2 ] ; then
	echo "Usage: filmbabescript featdir flobsdir"
	exit 1
fi	

if [ $1 = "--help" ] ; then
	echo "Usage: filmbabescript featdir flobsdir"
	exit
fi	

cd $1
featdir=`pwd`

flobsdir=$2

echo "$FSLDIR/bin/filmbabe --df=filtered_func_data --mask=mask --dm=design.mat --frf=design.frf --ld=filmbabe --ni=5 --ntar=3 --fd=$flobsdir"

$FSLDIR/bin/filmbabe --df=filtered_func_data --mask=mask --dm=design.mat --frf=design.frf --ld=filmbabe --ni=5 --ntar=3 --fd=$flobsdir

echo "$FSLDIR/bin/contrast_mgr -f design.fts filmbabe design.con"
$FSLDIR/bin/contrast_mgr -f design.fts filmbabe design.con

cd filmbabe

files=`$FSLDIR/bin/imglob zfstat*.*`
files=`$FSLDIR/bin/remove_ext $files`

echo "<HTML> <TITLE>Filmbabe results for $featdir </TITLE>" > report.html
echo "<BODY BACKGROUND=\"file:$FSLDIR/doc/images/fsl-bg.jpg\">" >> report.html
echo "<hr><CENTER><H1>Filmbabe results for <br> $featdir </H1><hr><p>" >> report.html
echo "<A HREF=$flobsdir/report.html> Optimal basis set report </A><p>" >> report.html

for filename in $files ; do
    fname=$filename
    echo "$FSLDIR/bin/mm --mask=mask --sdf=$fname --logdir=mm_$fname --ni=30 --zfstatmode"
    $FSLDIR/bin/mm --mask=mask --sdf=$fname --logdir=mm_$fname --ni=30 --zfstatmode;     
    echo "<A HREF=mm_$fname/MM.html> $fname mixture model fit results </A><p>"  >> report.html
done

echo "<img BORDER=0 SRC=\"gamAhist.png\">" >> report.html
echo "</CENTER><p>Analysis carried out by filmbabe, based on:<br>" >> report.html
echo "M.W. Woolrich, T.E.J. Behrens, and S.M. Smith. Constrained linear basis sets for HRF modelling using Variational Bayes. NeuroImage, 21:4(1748-1761) 2004." >> report.html

echo "<HR><FONT SIZE=1>This page produced automatically by filmbabescript - a part of <A HREF="http://www.fmrib.ox.ac.uk/fsl">FSL</A>.</FONT>" >>  report.html

echo "</BODY></HTML>" >> report.html

echo "View results at $featdir/filmbabe/report.html"

