#!/bin/sh

#   convert old FSL scripts from using avw* to using fsl*
#
#   Steve Smith, FMRIB Image Analysis Group
#
#   Copyright (C) 2007 University of Oxford
#
#   Part of FSL - FMRIB's Software Library
#   http://www.fmrib.ox.ac.uk/fsl
#   fsl@fmrib.ox.ac.uk
#   
#   Developed at FMRIB (Oxford Centre for Functional Magnetic Resonance
#   Imaging of the Brain), Department of Clinical Neurology, Oxford
#   University, Oxford, UK
#   
#   
#   LICENCE
#   
#   FMRIB Software Library, Release 4.0 (c) 2007, The University of
#   Oxford (the "Software")
#   
#   The Software remains the property of the University of Oxford ("the
#   University").
#   
#   The Software is distributed "AS IS" under this Licence solely for
#   non-commercial use in the hope that it will be useful, but in order
#   that the University as a charitable foundation protects its assets for
#   the benefit of its educational and research purposes, the University
#   makes clear that no condition is made or to be implied, nor is any
#   warranty given or to be implied, as to the accuracy of the Software,
#   or that it will be suitable for any particular purpose or for use
#   under any specific conditions. Furthermore, the University disclaims
#   all responsibility for the use which is made of the Software. It
#   further disclaims any liability for the outcomes arising from using
#   the Software.
#   
#   The Licensee agrees to indemnify the University and hold the
#   University harmless from and against any and all claims, damages and
#   liabilities asserted by third parties (including claims for
#   negligence) which arise directly or indirectly from the use of the
#   Software or the sale of any products based on the Software.
#   
#   No part of the Software may be reproduced, modified, transmitted or
#   transferred in any form or by any means, electronic or mechanical,
#   without the express permission of the University. The permission of
#   the University is not required if the said reproduction, modification,
#   transmission or transference is done without financial return, the
#   conditions of this Licence are imposed upon the receiver of the
#   product, and all original and amended source code is included in any
#   transmitted product. You may be held legally responsible for any
#   copyright infringement that is caused or encouraged by your failure to
#   abide by these terms and conditions.
#   
#   You are not permitted under this Licence to use this Software
#   commercially. Use for which any financial return is received shall be
#   defined as commercial use, and includes (1) integration of all or part
#   of the source code or the Software into a product for sale or license
#   by or on behalf of Licensee to third parties or (2) use of the
#   Software or any derivative of it for research with the final aim of
#   developing software products for sale or license to a third party or
#   (3) use of the Software or any derivative of it for research with the
#   final aim of developing non-software products for sale or license to a
#   third party, or (4) use of the Software to provide any service to an
#   external organisation for which payment is received. If you are
#   interested in using the Software commercially, please contact Isis
#   Innovation Limited ("Isis"), the technology transfer company of the
#   University, to negotiate a licence. Contact details are:
#   innovation@isis.ox.ac.uk quoting reference DE/1112.

if [ $# -lt 1 ] ; then
  echo "Usage: $0 [list of scripts to convert]" ;
  exit 1 ;
fi

for s in $@ ; do

    echo "
----- Processing script $s (will create backup in ${s}_avw)"

    /bin/cp $s ${s}_avw

    # remove "++"
    for p in avw2ascii avwcc avwcpgeom avwcreatehd avwhd avwinterleave avwmaths avwmerge avwnvols avwroi avwsplit avwstats ; do
	sed "s/${p}++/${p}/g" $s > ${s}_tmp ; /bin/mv ${s}_tmp $s
    done

    # convert "avw" to "fsl"
    for p in avw2afni avw2ascii avwanimate avwcc avwcheck avwchfiletype avwchpixdim avwcomplex avwconv avwcpgeom avwcreatehd avwedithd avwfft avwfill avwhd avwinfo avwinterleave avwmaths avwmeants avwmerge avwnvols avworient avwpspec avwroi avwsize avwslice avwsplit avwstats avwswapdim avwval ; do
	q=`echo $p | sed 's/avw/fsl/g'`
	sed "s/${p}/${q}/g" $s > ${s}_tmp ; /bin/mv ${s}_tmp $s
    done

    # convert MNI152 references
    sed "s/etc\/standard/data\/standard/g" $s > ${s}_tmp ; /bin/mv ${s}_tmp $s
    sed "s/avg152T1_brain_mask_dil2/avg152T1_brain_mask_dil/g" $s > ${s}_tmp ; /bin/mv ${s}_tmp $s
    sed "s/avg152T1/MNI152_T1_2mm/g" $s > ${s}_tmp ; /bin/mv ${s}_tmp $s

    # warn about "ip"
    w=`cat $s | grep "ip "`
    if [ "$w" != "" ] ; then
	echo "--- Warning - hand-editing may be required in file ${s} if the following line(s) contain calls to the \"ip\" program,
    as ip no londer exists in FSL (use fslmaths instead):
$w"
    fi

    # warn about "-ero2"
    w=`cat $s | grep fslmaths | grep " -ero2 "`
    if [ "$w" != "" ] ; then
	echo "--- Warning - hand-editing may be required in file ${s}; in the following line, probably change \"-ero2\" to \"-kernel 2D -ero\"
$w"
    fi

    # warn about "-dil2"
    w=`cat $s | grep fslmaths | grep " -dil2 "`
    if [ "$w" != "" ] ; then
	echo "--- Warning - hand-editing may be required in file ${s}; in the following line, probably change \"-dil2\" to \"-kernel 2D -dilF\"
$w"
    fi

    # warn about "-dil"
    w=`cat $s | grep fslmaths | grep " -dil "`
    if [ "$w" != "" ] ; then
	echo "--- Warning - hand-editing may be required in file ${s}; in the following line, probably change \"-dil\" to \"-dilF\"
$w"
    fi

    # warn about "susan_smooth"
    w=`cat $s | grep susan_smooth`
    if [ "$w" != "" ] ; then
	echo "--- Warning - hand-editing may be required in file ${s}; in the following line, probably change \"susan_smooth\" to \"susan\" note that argument order has changed
$w"
    fi

    # warn about datatype changing in avwmaths_*
    for p in fsl2ascii fslcc fslinterleave fslmaths fslroi bet ; do
	w=`cat $s | grep ${p}_8UI`
	if [ "$w" != "" ] ; then
	    echo "--- hand-editing required in ${s} : in the following line(s), change \"${p}_8UI\" to \"${p}\" and end the command with \"-odt char\""
	    echo $w
	fi
	w=`cat $s | grep ${p}_16SI`
	if [ "$w" != "" ] ; then
	    echo "--- hand-editing required in ${s} : in the following line(s), change \"${p}_16SI\" to \"${p}\" and end the command with \"-odt short\""
	    echo $w
	fi
	w=`cat $s | grep ${p}_32SI`
	if [ "$w" != "" ] ; then
	    echo "--- hand-editing required in ${s} : in the following line(s), change \"${p}_32SI\" to \"${p}\" and end the command with \"-odt int\""
	    echo $w
	fi
	w=`cat $s | grep ${p}_32R`
	if [ "$w" != "" ] ; then
	    echo "--- hand-editing required in ${s} : in the following line(s), change \"${p}_32R\" to \"${p}\" and end the command with \"-odt float\""
	    echo $w
	fi
	w=`cat $s | grep ${p}_64R`
	if [ "$w" != "" ] ; then
	    echo "--- hand-editing required in ${s} : in the following line(s), change \"${p}_64R\" to \"${p}\" and end the command with \"-odt double\""
	    echo $w
	fi
    done

done  

