#!/bin/sh

#   fslanimate - make gif animation from time series (3 views)
# 
#   Stephen Smith and Mark Jenkinson, FMRIB Image Analysis Group
#
#   Copyright (C) 1999-2004 University of Oxford
#
#   Part of FSL - FMRIB's Software Library
#   http://www.fmrib.ox.ac.uk/fsl
#   fsl@fmrib.ox.ac.uk
#   
#   Developed at FMRIB (Oxford Centre for Functional Magnetic Resonance
#   Imaging of the Brain), Department of Clinical Neurology, Oxford
#   University, Oxford, UK
#   
#   
#   LICENCE
#   
#   FMRIB Software Library, Release 4.0 (c) 2007, The University of
#   Oxford (the "Software")
#   
#   The Software remains the property of the University of Oxford ("the
#   University").
#   
#   The Software is distributed "AS IS" under this Licence solely for
#   non-commercial use in the hope that it will be useful, but in order
#   that the University as a charitable foundation protects its assets for
#   the benefit of its educational and research purposes, the University
#   makes clear that no condition is made or to be implied, nor is any
#   warranty given or to be implied, as to the accuracy of the Software,
#   or that it will be suitable for any particular purpose or for use
#   under any specific conditions. Furthermore, the University disclaims
#   all responsibility for the use which is made of the Software. It
#   further disclaims any liability for the outcomes arising from using
#   the Software.
#   
#   The Licensee agrees to indemnify the University and hold the
#   University harmless from and against any and all claims, damages and
#   liabilities asserted by third parties (including claims for
#   negligence) which arise directly or indirectly from the use of the
#   Software or the sale of any products based on the Software.
#   
#   No part of the Software may be reproduced, modified, transmitted or
#   transferred in any form or by any means, electronic or mechanical,
#   without the express permission of the University. The permission of
#   the University is not required if the said reproduction, modification,
#   transmission or transference is done without financial return, the
#   conditions of this Licence are imposed upon the receiver of the
#   product, and all original and amended source code is included in any
#   transmitted product. You may be held legally responsible for any
#   copyright infringement that is caused or encouraged by your failure to
#   abide by these terms and conditions.
#   
#   You are not permitted under this Licence to use this Software
#   commercially. Use for which any financial return is received shall be
#   defined as commercial use, and includes (1) integration of all or part
#   of the source code or the Software into a product for sale or license
#   by or on behalf of Licensee to third parties or (2) use of the
#   Software or any derivative of it for research with the final aim of
#   developing software products for sale or license to a third party or
#   (3) use of the Software or any derivative of it for research with the
#   final aim of developing non-software products for sale or license to a
#   third party, or (4) use of the Software to provide any service to an
#   external organisation for which payment is received. If you are
#   interested in using the Software commercially, please contact Isis
#   Innovation Limited ("Isis"), the technology transfer company of the
#   University, to negotiate a licence. Contact details are:
#   innovation@isis.ox.ac.uk quoting reference DE/1112.

num=0; export num;
if [ $# -lt 2 ] ; then
  echo "Usage: fslanimate <input> <output> [tmpdir]" ;
  exit -1;
fi

im=`${FSLDIR}/bin/remove_ext $1`; export im;
im=`basename $im`; export im;
iout=`basename $2 .gif`; export iout;

delete=true; export delete;
tmpdir=/tmp/fslanimate_$$; export tmpdir;
if [ $# -eq 3 ] ; then
  tmpdir=$3; export tmpdir;
  delete=false; export delete;
fi

cwd=`pwd`; export cwd
imdir=`dirname $1 | sed 's/^\.\./.\/../'`; export imdir
if [ "X"`echo $imdir | grep '^\.'`"X" != "XX" ] ; then
  imdir="$cwd/$imdir"; export imdir;
fi
imoutdir=`dirname $2 | sed 's/^\.\./.\/../'`; export imoutdir;
if [ "X"`echo $imoutdir | grep '^\.'`"X" != "XX" ] ; then
  imoutdir="$cwd/$imoutdir"; export imoutdir;
fi

if [ ! -d $tmpdir ] ; then
  mkdir $tmpdir ;
else
  delete=false;  export delete;
fi

# check if it is 4D or not

ntime=`$FSLDIR/bin/fslval $imdir/$im dim4`; export ntime;
if [ $ntime -le 1 ] ; then
  $FSLDIR/bin/sliceanimate $imdir/$im ;
  mv $imdir/${im}_sliceanim.gif $imoutdir/${iout}.gif ;
else

$FSLDIR/bin/imln $imdir/$im $tmpdir/$im
cd $tmpdir 

$FSLDIR/bin/fslsplit $im 
for fnm in `$FSLDIR/bin/imglob vol*` ; do
  num=`echo $fnm | sed 's/vol//'`;  export num;
  echo $num; 
  $FSLDIR/bin/slicer $fnm -s 2 -a ${iout}_$num.png
  ${FSLDIR}/bin/pngappend ${iout}_$num.png ${iout}_$num.gif
  rm -f ${iout}_$num.png
done

$FSLDIR/bin/whirlgif -o ${iout}.gif -time 15 -loop 0 ${iout}_*.gif

mv $tmpdir/${iout}.gif ${imoutdir}/${iout}.gif

fi

# make a little web page that can be viewed
touch ${imoutdir}/${iout}.html
echo '<html>' >> ${imoutdir}/${iout}.html
echo '<body>' >> ${imoutdir}/${iout}.html
echo '<img src="'${iout}.gif'">' >> ${imoutdir}/${iout}.html
echo '</body>' >> ${imoutdir}/${iout}.html
echo '</html>' >> ${imoutdir}/${iout}.html export im;

# clean up
cd $cwd
if [ $delete = "true" ] ; then
  rm -rf $tmpdir
fi


