#!/bin/sh

#   basic image handling scripts
#
#   Christian Beckmann and Mark Jenkinson
#   FMRIB Image Analysis Group
#
#   Copyright (C) 1999-2004 University of Oxford
#
#   Part of FSL - FMRIB's Software Library
#   http://www.fmrib.ox.ac.uk/fsl
#   fsl@fmrib.ox.ac.uk
#   
#   Developed at FMRIB (Oxford Centre for Functional Magnetic Resonance
#   Imaging of the Brain), Department of Clinical Neurology, Oxford
#   University, Oxford, UK
#   
#   
#   LICENCE
#   
#   FMRIB Software Library, Release 4.0 (c) 2007, The University of
#   Oxford (the "Software")
#   
#   The Software remains the property of the University of Oxford ("the
#   University").
#   
#   The Software is distributed "AS IS" under this Licence solely for
#   non-commercial use in the hope that it will be useful, but in order
#   that the University as a charitable foundation protects its assets for
#   the benefit of its educational and research purposes, the University
#   makes clear that no condition is made or to be implied, nor is any
#   warranty given or to be implied, as to the accuracy of the Software,
#   or that it will be suitable for any particular purpose or for use
#   under any specific conditions. Furthermore, the University disclaims
#   all responsibility for the use which is made of the Software. It
#   further disclaims any liability for the outcomes arising from using
#   the Software.
#   
#   The Licensee agrees to indemnify the University and hold the
#   University harmless from and against any and all claims, damages and
#   liabilities asserted by third parties (including claims for
#   negligence) which arise directly or indirectly from the use of the
#   Software or the sale of any products based on the Software.
#   
#   No part of the Software may be reproduced, modified, transmitted or
#   transferred in any form or by any means, electronic or mechanical,
#   without the express permission of the University. The permission of
#   the University is not required if the said reproduction, modification,
#   transmission or transference is done without financial return, the
#   conditions of this Licence are imposed upon the receiver of the
#   product, and all original and amended source code is included in any
#   transmitted product. You may be held legally responsible for any
#   copyright infringement that is caused or encouraged by your failure to
#   abide by these terms and conditions.
#   
#   You are not permitted under this Licence to use this Software
#   commercially. Use for which any financial return is received shall be
#   defined as commercial use, and includes (1) integration of all or part
#   of the source code or the Software into a product for sale or license
#   by or on behalf of Licensee to third parties or (2) use of the
#   Software or any derivative of it for research with the final aim of
#   developing software products for sale or license to a third party or
#   (3) use of the Software or any derivative of it for research with the
#   final aim of developing non-software products for sale or license to a
#   third party, or (4) use of the Software to provide any service to an
#   external organisation for which payment is received. If you are
#   interested in using the Software commercially, please contact Isis
#   Innovation Limited ("Isis"), the technology transfer company of the
#   University, to negotiate a licence. Contact details are:
#   innovation@isis.ox.ac.uk quoting reference DE/1112.

Usage() {
    echo ""
    echo "Usage: fsledithd <input> [editor]"
    echo ""
    exit 1
}

[ "$1" = "" ] && Usage

if [ _$FSLDIR = _ ] ; then
    FSLDIR=/usr/local/fsl
    export FSLDIR
fi

if [ X$FSLEDITOR = X ] ; then
    FSLEDITOR=nano
fi
if [ $# -ge 2 ] ; then
    FSLEDITOR=$2
fi

tmpbase=`${FSLDIR}/bin/tmpnam`;
tmpbase2=`${FSLDIR}/bin/tmpnam`;

# put in helpful comments at the start
echo "# FSLEDITHD" > ${tmpbase}
echo "# This text file contains the header information for an Analyze or Nifti file" >> ${tmpbase}
echo "# Simply edit this file then save it and the header will be regenerated" >> ${tmpbase}
echo "# All lines starting with the hash (#) character, like this line, will be ignored" >> ${tmpbase}
echo "# Ensure that all lines intended to set values take the form: name = 'value' " >> ${tmpbase}
echo "# Note that if the file is Analyze then many settings will be ignored" >> ${tmpbase}
echo "# Further note that the filetype cannot be changed by this program" >> ${tmpbase}
echo "#   i.e. changing the nifti_type has no effect" >> ${tmpbase}
echo " " >> ${tmpbase}

# generate the xml-style header with fslhd
${FSLDIR}/bin/fslhd -x $1 | grep -v '/>' | grep -v '_filename' | grep -v '[^t]_name' | grep -v 'nvox' | grep -v 'to_ijk' | grep -v 'form_.*orientation' | grep -v 'qto_' > ${tmpbase2}
# exit if the above didn't generate a decent file
if [ `cat ${tmpbase} | wc -l` -le 1 ] ; then
  exit 0;
fi
# tack onto initial comments
cat ${tmpbase2} >> ${tmpbase}
# add stuff before end
echo "# Many fields require codes to be set (e.g. sform_code, qform_code, intent_code)" >> ${tmpbase}
echo "# Valid values are:" >> ${tmpbase}
echo "#   sform_code (or qform) :- 0=UNKNOWN, 1=SCANNER_ANAT, 2=ALIGNED_ANAT, 3=TALAIRACH, 4=MNI_152" >> ${tmpbase}
echo "#   xyz_units :- 1=METER, 2=MM, 3=MICRON " >> ${tmpbase}
echo "#   t_units :- 8=SEC, 16=MSEC, 24=USEC, 32=HZ, 40=PPM, 48=RADS" >> ${tmpbase}
echo "#   intent_code :- 0=NONE, 2=CORRELATION, 3=TTEST, 4=FTEST, 5=ZSCORE, 6=CHISQ, ..." >> ${tmpbase}
echo "#                  22=PVAL, 23=LOGPVAL, 24=LOG10PVAL, 1001=ESTIMATE, 1002=LABEL (incl masks)" >> ${tmpbase}
echo "#                  Other codes can be found in the $FSLDIR/src/niftiio/nifti1.h file" >> ${tmpbase}
echo " " >> ${tmpbase}
# close the xml-style part
echo "/>" >> ${tmpbase}

# edit header, reprocess and pass onto fslcreatehd
${FSLEDITOR} ${tmpbase}
cat ${tmpbase} | grep -v '^[ 	]*#' | grep -v '^[ 	]*$' > ${tmpbase2}
${FSLDIR}/bin/fslcreatehd ${tmpbase2} $1

/bin/rm ${tmpbase} ${tmpbase2}

