#!/bin/sh

#   tbss_sym - make symmetric skeleton for TBSS left-right testing
#
#   Stephen Smith, FMRIB Image Analysis Group
#
#   Copyright (C) 2008-2009 University of Oxford
#
#   Part of FSL - FMRIB's Software Library
#   http://www.fmrib.ox.ac.uk/fsl
#   fsl@fmrib.ox.ac.uk
#   
#   Developed at FMRIB (Oxford Centre for Functional Magnetic Resonance
#   Imaging of the Brain), Department of Clinical Neurology, Oxford
#   University, Oxford, UK
#   
#   
#   LICENCE
#   
#   FMRIB Software Library, Release 4.0 (c) 2007, The University of
#   Oxford (the "Software")
#   
#   The Software remains the property of the University of Oxford ("the
#   University").
#   
#   The Software is distributed "AS IS" under this Licence solely for
#   non-commercial use in the hope that it will be useful, but in order
#   that the University as a charitable foundation protects its assets for
#   the benefit of its educational and research purposes, the University
#   makes clear that no condition is made or to be implied, nor is any
#   warranty given or to be implied, as to the accuracy of the Software,
#   or that it will be suitable for any particular purpose or for use
#   under any specific conditions. Furthermore, the University disclaims
#   all responsibility for the use which is made of the Software. It
#   further disclaims any liability for the outcomes arising from using
#   the Software.
#   
#   The Licensee agrees to indemnify the University and hold the
#   University harmless from and against any and all claims, damages and
#   liabilities asserted by third parties (including claims for
#   negligence) which arise directly or indirectly from the use of the
#   Software or the sale of any products based on the Software.
#   
#   No part of the Software may be reproduced, modified, transmitted or
#   transferred in any form or by any means, electronic or mechanical,
#   without the express permission of the University. The permission of
#   the University is not required if the said reproduction, modification,
#   transmission or transference is done without financial return, the
#   conditions of this Licence are imposed upon the receiver of the
#   product, and all original and amended source code is included in any
#   transmitted product. You may be held legally responsible for any
#   copyright infringement that is caused or encouraged by your failure to
#   abide by these terms and conditions.
#   
#   You are not permitted under this Licence to use this Software
#   commercially. Use for which any financial return is received shall be
#   defined as commercial use, and includes (1) integration of all or part
#   of the source code or the Software into a product for sale or license
#   by or on behalf of Licensee to third parties or (2) use of the
#   Software or any derivative of it for research with the final aim of
#   developing software products for sale or license to a third party or
#   (3) use of the Software or any derivative of it for research with the
#   final aim of developing non-software products for sale or license to a
#   third party, or (4) use of the Software to provide any service to an
#   external organisation for which payment is received. If you are
#   interested in using the Software commercially, please contact Isis
#   Innovation Limited ("Isis"), the technology transfer company of the
#   University, to negotiate a licence. Contact details are:
#   innovation@isis.ox.ac.uk quoting reference DE/1112.

Usage () {
    echo ""
    echo "Usage: tbss_sym <image-rootname>"
    echo "e.g. tbss_sym FA"
    echo "e.g. tbss_sym L2"
    echo ""
    exit 1
}

[ "$1" = "" ] && Usage

thresh=`cat thresh.txt`
ALTIM=$1

if [ `${FSLDIR}/bin/imtest mean_FA_symmetrised_skeleton_mask_dst` -eq 0 ]; then

    echo "creating a symmetrised skeleton"
    $FSLDIR/bin/fslmaths mean_FA_skeleton -thr $thresh -bin -dilF grotsym_dilated
    $FSLDIR/bin/fslswapdim mean_FA -x y z grotsym > /dev/null
    $FSLDIR/bin/fslmaths mean_FA -mas grotsym -add grotsym -div 2 mean_FA_symmetrised
    $FSLDIR/bin/tbss_skeleton -i mean_FA_symmetrised -o grotsym_symmetrised_skeleton
    $FSLDIR/bin/fslmaths grotsym_symmetrised_skeleton -thr $thresh -mas grotsym_dilated grotsym_symmetrised_skeleton
    $FSLDIR/bin/fslswapdim grotsym_symmetrised_skeleton -x y z grotsym > /dev/null
    $FSLDIR/bin/fslmaths grotsym_symmetrised_skeleton -mas grotsym mean_FA_symmetrised_skeleton
    $FSLDIR/bin/fslmaths mean_FA_symmetrised_skeleton -bin mean_FA_symmetrised_skeleton_mask

    echo "creating symmetrised skeleton distancemap"
    ${FSLDIR}/bin/fslmaths mean_FA_mask -mul -1 -add 1 -add mean_FA_symmetrised_skeleton_mask mean_FA_symmetrised_skeleton_mask_dst
    ${FSLDIR}/bin/distancemap -i mean_FA_symmetrised_skeleton_mask_dst -o mean_FA_symmetrised_skeleton_mask_dst

fi

echo "projecting all FA data onto symmetrised skeleton"
if [ $ALTIM != "FA" ]; then
    altim="-a all_${ALTIM}"
fi
${FSLDIR}/bin/tbss_skeleton -i mean_FA_symmetrised -p $thresh mean_FA_symmetrised_skeleton_mask_dst ${FSLDIR}/data/standard/LowerCingulum_1mm all_FA all_${ALTIM}_symmetrised_skeletonised $altim -s mean_FA_symmetrised_skeleton

echo "flipping, substracting and half-masking 4D skeletonised FA"
$FSLDIR/bin/fslswapdim all_${ALTIM}_symmetrised_skeletonised -x y z grotsym_all_${ALTIM}_symmetrised_flipped > /dev/null
$FSLDIR/bin/fslmaths all_${ALTIM}_symmetrised_skeletonised -sub grotsym_all_${ALTIM}_symmetrised_flipped -roi 91 91 0 218 0 182 0 `$FSLDIR/bin/fslval all_FA_skeletonised dim4` all_${ALTIM}_skeletonised_left_minus_right

$FSLDIR/bin/imrm grotsym*

