#!/bin/sh

#   flirt_average - align more than one raw images to each other and average to improve SNR etc.
#
#   Stephen Smith, FMRIB Image Analysis Group
#
#   Copyright (C) 2007 University of Oxford
#
#   Part of FSL - FMRIB's Software Library
#   http://www.fmrib.ox.ac.uk/fsl
#   fsl@fmrib.ox.ac.uk
#   
#   Developed at FMRIB (Oxford Centre for Functional Magnetic Resonance
#   Imaging of the Brain), Department of Clinical Neurology, Oxford
#   University, Oxford, UK
#   
#   
#   LICENCE
#   
#   FMRIB Software Library, Release 4.0 (c) 2007, The University of
#   Oxford (the "Software")
#   
#   The Software remains the property of the University of Oxford ("the
#   University").
#   
#   The Software is distributed "AS IS" under this Licence solely for
#   non-commercial use in the hope that it will be useful, but in order
#   that the University as a charitable foundation protects its assets for
#   the benefit of its educational and research purposes, the University
#   makes clear that no condition is made or to be implied, nor is any
#   warranty given or to be implied, as to the accuracy of the Software,
#   or that it will be suitable for any particular purpose or for use
#   under any specific conditions. Furthermore, the University disclaims
#   all responsibility for the use which is made of the Software. It
#   further disclaims any liability for the outcomes arising from using
#   the Software.
#   
#   The Licensee agrees to indemnify the University and hold the
#   University harmless from and against any and all claims, damages and
#   liabilities asserted by third parties (including claims for
#   negligence) which arise directly or indirectly from the use of the
#   Software or the sale of any products based on the Software.
#   
#   No part of the Software may be reproduced, modified, transmitted or
#   transferred in any form or by any means, electronic or mechanical,
#   without the express permission of the University. The permission of
#   the University is not required if the said reproduction, modification,
#   transmission or transference is done without financial return, the
#   conditions of this Licence are imposed upon the receiver of the
#   product, and all original and amended source code is included in any
#   transmitted product. You may be held legally responsible for any
#   copyright infringement that is caused or encouraged by your failure to
#   abide by these terms and conditions.
#   
#   You are not permitted under this Licence to use this Software
#   commercially. Use for which any financial return is received shall be
#   defined as commercial use, and includes (1) integration of all or part
#   of the source code or the Software into a product for sale or license
#   by or on behalf of Licensee to third parties or (2) use of the
#   Software or any derivative of it for research with the final aim of
#   developing software products for sale or license to a third party or
#   (3) use of the Software or any derivative of it for research with the
#   final aim of developing non-software products for sale or license to a
#   third party, or (4) use of the Software to provide any service to an
#   external organisation for which payment is received. If you are
#   interested in using the Software commercially, please contact Isis
#   Innovation Limited ("Isis"), the technology transfer company of the
#   University, to negotiate a licence. Contact details are:
#   innovation@isis.ox.ac.uk quoting reference DE/1112.

Usage() {
    echo ""
    echo "Usage: flirt_average <Ninputs> <input1> <input2> ...... <output> [options] [flirt-options]"
    echo ""
    echo "Options:"
    echo " -FAref <ref_image> : reference image to use instead of first input"
    echo ""
    echo "e.g.  flirt_average 3 rawT1_1 rawT1_2 rawT1_3 averageT1"
    echo "e.g.  flirt_average 2 rawT1_1 rawT1_2 averageT1 -FAref /usr/local/fsl/data/standard/MNI152_T1_2mm -FAdim 1 -cost normcorr"
    echo ""
    exit 1
}

[ _$4 = _ ] && Usage

N=$1
shift

reference=`${FSLDIR}/bin/remove_ext $1`

i=1
while [ $i -le $N ] ; do
    imagelist="$imagelist `${FSLDIR}/bin/remove_ext $1`"
    shift
    i=`echo "$i 1 + p" | dc -`
done

output=$1
shift

while [ _$1 != _ ] ; do

    if [ $1 = -FAref ] ; then
        reference=`${FSLDIR}/bin/remove_ext $2`
        shift 2

    else
	flirtoptions="$flirtoptions $1"
	shift
    fi
done

for input in $imagelist ; do
    if [ $input = $reference ] ; then
	outlist=$input
    else
	${FSLDIR}/bin/flirt -in $input -ref $reference -out ${input}_2ref -omat ${input}_2ref.mat -nosearch -interp sinc $flirtoptions
	outlist="$outlist ${input}_2ref"
    fi
done

fslmerge -t $output $outlist
fslmaths $output -Tmean $output

/bin/rm *_2ref*

